package com.example.VehicleStore.search.sort.rental;

public enum RentalSort {

    START_DATE_ASC,
    START_DATE_DESC,
    RETURN_DATE_ASC,
    RETURN_DATE_DESC,
    EXPIRATION_DATE_ASC,
    EXPIRATION_DATE_DESC,
    RENTAL_PRICE_ASC,
    RENTAL_PRICE_DESC,
    RENTAL_STATUS_ASC,
    RENTAL_STATUS_DESC,
    CLIENT_NAME_ASC,
    CLIENT_NAME_DESC,
    CAR_BRAND_ASC,
    CAR_BRAND_DESC,
    MOTORCYCLE_BRAND_ASC,
    MOTORCYCLE_BRAND_DESC,
    PAYMENT_METHOD_ASC,
    PAYMENT_METHOD_DESC,
    DISCOUNT_ASC,
    DISCOUNT_DESC,
    LOCATION_ASC,
    LOCATION_DESC

}
