package com.example.VehicleStore.search.sort.purchase;

public enum PurchaseSort {

    PURCHASE_DATE_ASC,
    PURCHASE_DATE_DESC,
    PURCHASE_PRICE_ASC,
    PURCHASE_PRICE_DESC,
    DISCOUNT_ASC,
    DISCOUNT_DESC,
    CLIENT_NAME_ASC,
    CLIENT_NAME_DESC,
    SELLER_NAME_ASC,
    SELLER_NAME_DESC,
    PURCHASE_STATUS_ASC,
    PURCHASE_STATUS_DESC,
    PURCHASE_TYPE_ASC,
    PURCHASE_TYPE_DESC,
    LOCATION_ASC,
    LOCATION_DESC,
    PAYMENT_METHOD_ASC,
    PAYMENT_METHOD_DESC,
    TRANSACTION_ID_ASC,
    TRANSACTION_ID_DESC
}
